name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repo
      - uses: actions/checkout@v2

      # Step 2: Sync files to S3 using jakejarvis/s3-sync-action
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'Seanle'
      
      # Step 3: Invoke your Lambda function
      - name: Invoke Lambda (for CloudFront invalidation or any other task)
        run: |
          # Install AWS CLI if not already available (ubuntu-latest usually has it)
          sudo apt-get update && sudo apt-get install -y awscli

          # Invoke the Lambda function
          aws lambda invoke \
            --function-name DailySeanleCloudfrontInvalidation \
            --region us-east-2 \
            --payload '{}' \
            output.json

          echo "Lambda function invoked. Check output.json for response."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2' 
